!=====================================================================
!
!               S p e c f e m 3 D  V e r s i o n  3 . 0
!               ---------------------------------------
!
!     Main historical authors: Dimitri Komatitsch and Jeroen Tromp
!                              CNRS, France
!                       and Princeton University, USA
!                 (there are currently many more authors!)
!                           (c) October 2017
!
! This program is free software; you can redistribute it and/or modify
! it under the terms of the GNU General Public License as published by
! the Free Software Foundation; either version 3 of the License, or
! (at your option) any later version.
!
! This program is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License along
! with this program; if not, write to the Free Software Foundation, Inc.,
! 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
!
!=====================================================================
!
! United States and French Government Sponsorship Acknowledged.

  program xspecfem3D

  use specfem_par
  use specfem_par_ASKI

  implicit none

!=============================================================================!
!                                                                             !
!  specfem3D is a 3-D spectral-element solver for a local or regional model.  !
!  It uses a mesh generated by program generate_databases                     !
!                                                                             !
!=============================================================================!
!
! If you use this code for your own research, please cite at least one article
! written by the developers of the package, for instance:
!
! @ARTICLE{TrKoLi08,
! author = {Jeroen Tromp and Dimitri Komatitsch and Qinya Liu},
! title = {Spectral-Element and Adjoint Methods in Seismology},
! journal = {communications in Computational Physics},
! year = {2008},
! volume = {3},
! pages = {1-32},
! number = {1}}
!
! @ARTICLE{PeKoLuMaLeCaLeMaLiBlNiBaTr11,
! author = {Daniel Peter and Dimitri Komatitsch and Yang Luo and Roland Martin
!     and Nicolas {Le Goff} and Emanuele Casarotti and Pieyre {Le Loher}
!     and Federica Magnoni and Qinya Liu and C\'eline Blitz and Tarje Nissen-Meyer
!     and Piero Basini and Jeroen Tromp},
! title = {Forward and adjoint simulations of seismic wave propagation on fully
!     unstructured hexahedral meshes},
! journal={Geophys. J. Int.},
! year = {2011},
! volume = {186},
! pages = {721-739},
! number = {2},
! doi = {10.1111/j.1365-246X.2011.05044.x}}
!
! or
!
! @ARTICLE{VaCaSaKoVi99,
! author = {R. Vai and J. M. Castillo-Covarrubias and F. J. S\'anchez-Sesma and
! D. Komatitsch and J. P. Vilotte},
! title = {Elastic wave propagation in an irregularly layered medium},
! journal = {Soil Dynamics and Earthquake Engineering},
! year = {1999},
! volume = {18},
! pages = {11-18},
! number = {1},
! doi = {10.1016/S0267-7261(98)00027-X}}
!
! @ARTICLE{LeChKoHuTr09,
! author = {Shiann Jong Lee and Yu Chang Chan and Dimitri Komatitsch and Bor
! Shouh Huang and Jeroen Tromp},
! title = {Effects of realistic surface topography on seismic ground motion
! in the {Y}angminshan region of {T}aiwan based upon the spectral-element
! method and {LiDAR DTM}},
! journal = {Bull. Seismol. Soc. Am.},
! year = {2009},
! volume = {99},
! pages = {681-693},
! number = {2A},
! doi = {10.1785/0120080264}}
!
! @ARTICLE{LeChLiKoHuTr08,
! author = {Shiann Jong Lee and How Wei Chen and Qinya Liu and Dimitri Komatitsch
! and Bor Shouh Huang and Jeroen Tromp},
! title = {Three-Dimensional Simulations of Seismic Wave Propagation in the
! {T}aipei Basin with Realistic Topography Based upon the Spectral-Element Method},
! journal = {Bull. Seismol. Soc. Am.},
! year = {2008},
! volume = {98},
! pages = {253-264},
! number = {1},
! doi = {10.1785/0120070033}}
!
! @ARTICLE{LeKoHuTr09,
! author = {S. J. Lee and Dimitri Komatitsch and B. S. Huang and J. Tromp},
! title = {Effects of topography on seismic wave propagation: An example from
! northern {T}aiwan},
! journal = {Bull. Seismol. Soc. Am.},
! year = {2009},
! volume = {99},
! pages = {314-325},
! number = {1},
! doi = {10.1785/0120080020}}
!
! @ARTICLE{KoErGoMi10,
! author = {Dimitri Komatitsch and Gordon Erlebacher and Dominik G\"oddeke and
! David Mich\'ea},
! title = {High-order finite-element seismic wave propagation modeling with
! {MPI} on a large {GPU} cluster},
! journal = {J. Comput. Phys.},
! year = {2010},
! volume = {229},
! pages = {7692-7714},
! number = {20},
! doi = {10.1016/j.jcp.2010.06.024}}
!
! @ARTICLE{KoGoErMi10,
! author = {Dimitri Komatitsch and Dominik G\"oddeke and Gordon Erlebacher and
! David Mich\'ea},
! title = {Modeling the propagation of elastic waves using spectral elements
! on a cluster of 192 {GPU}s},
! journal = {Computer Science Research and Development},
! year = {2010},
! volume = {25},
! pages = {75-82},
! number = {1-2},
! doi = {10.1007/s00450-010-0109-1}}
!
! @ARTICLE{KoMiEr09,
! author = {Dimitri Komatitsch and David Mich\'ea and Gordon Erlebacher},
! title = {Porting a high-order finite-element earthquake modeling application
! to {NVIDIA} graphics cards using {CUDA}},
! journal = {Journal of Parallel and Distributed Computing},
! year = {2009},
! volume = {69},
! pages = {451-460},
! number = {5},
! doi = {10.1016/j.jpdc.2009.01.006}}
!
! @ARTICLE{LiPoKoTr04,
! author = {Qinya Liu and Jascha Polet and Dimitri Komatitsch and Jeroen Tromp},
! title = {Spectral-element moment tensor inversions for earthquakes in {S}outhern {C}alifornia},
! journal={Bull. Seismol. Soc. Am.},
! year = {2004},
! volume = {94},
! pages = {1748-1761},
! number = {5},
! doi = {10.1785/012004038}}
!
! @INCOLLECTION{ChKoViCaVaFe07,
! author = {Emmanuel Chaljub and Dimitri Komatitsch and Jean-Pierre Vilotte and
! Yann Capdeville and Bernard Valette and Gaetano Festa},
! title = {Spectral Element Analysis in Seismology},
! booktitle = {Advances in Wave Propagation in Heterogeneous Media},
! publisher = {Elsevier - Academic Press},
! year = {2007},
! editor = {Ru-Shan Wu and Val\'erie Maupin},
! volume = {48},
! series = {Advances in Geophysics},
! pages = {365-419}}
!
! @ARTICLE{KoVi98,
! author={D. Komatitsch and J. P. Vilotte},
! title={The spectral-element method: an efficient tool to simulate the seismic response of 2{D} and 3{D} geological structures},
! journal={Bull. Seismol. Soc. Am.},
! year=1998,
! volume=88,
! number=2,
! pages={368-392}}
!
! @ARTICLE{KoTr99,
! author={D. Komatitsch and J. Tromp},
! year=1999,
! title={Introduction to the spectral-element method for 3-{D} seismic wave propagation},
! journal={Geophys. J. Int.},
! volume=139,
! number=3,
! pages={806-822},
! doi={10.1046/j.1365-246x.1999.00967.x}}
!
! @ARTICLE{KoLiTrSuStSh04,
! author={Dimitri Komatitsch and Qinya Liu and Jeroen Tromp and Peter S\"{u}ss
!   and Christiane Stidham and John H. Shaw},
! year=2004,
! title={Simulations of Ground Motion in the {L}os {A}ngeles {B}asin
!   based upon the Spectral-Element Method},
! journal={Bull. Seism. Soc. Am.},
! volume=94,
! number=1,
! pages={187-206}}
!
! and/or another article from http://web.univ-pau.fr/~dkomati1/publications.html
!
!
! If you use the kernel capabilities of the code, please cite at least one article
! written by the developers of the package, for instance:
!
! @ARTICLE{TrKoLi08,
! author = {Jeroen Tromp and Dimitri Komatitsch and Qinya Liu},
! title = {Spectral-Element and Adjoint Methods in Seismology},
! journal = {communications in Computational Physics},
! year = {2008},
! volume = {3},
! pages = {1-32},
! number = {1}}
!
! @ARTICLE{PeKoLuMaLeCaLeMaLiBlNiBaTr11,
! author = {Daniel Peter and Dimitri Komatitsch and Yang Luo and Roland Martin
!     and Nicolas {Le Goff} and Emanuele Casarotti and Pieyre {Le Loher}
!     and Federica Magnoni and Qinya Liu and C\'eline Blitz and Tarje Nissen-Meyer
!     and Piero Basini and Jeroen Tromp},
! title = {Forward and adjoint simulations of seismic wave propagation on fully
!     unstructured hexahedral meshes},
! journal={Geophys. J. Int.},
! year = {2011},
! volume = {186},
! pages = {721-739},
! number = {2},
! doi = {10.1111/j.1365-246X.2011.05044.x}}
!
! or
!
! @ARTICLE{LiTr06,
! author={Qinya Liu and Jeroen Tromp},
! title={Finite-frequency kernels based on adjoint methods},
! journal={Bull. Seismol. Soc. Am.},
! year=2006,
! volume=96,
! number=6,
! pages={2383-2397},
! doi={10.1785/0120060041}}
!
!
! Reference frame - convention:
! ----------------------------
!
! The code uses the following convention for the reference frame:
!
!  - X axis is East
!  - Y axis is North
!  - Z axis is up
!
! Note that this convention is different from both the Aki-Richards convention
! and the Harvard CMT convention.
!
! Let us recall that the Aki-Richards convention is:
!
!  - X axis is North
!  - Y axis is East
!  - Z axis is down
!
! and that the Harvard CMT convention is:
!
!  - X axis is South
!  - Y axis is East
!  - Z axis is up
!
! To report bugs or suggest improvements to the code, please use our online
! bug tracking system at http://www.geodynamics.org/roundup .
!
! Evolution of the code:
! ---------------------
!
! MPI v. 3.0, December 2014: many developers.
! Convolutional PML, LDDRK time scheme, bulk attenuation support, simultaneous MPI runs,
! ADIOS file I/O support, coupling with external codes, new seismogram names,
! Deville routines for additional GLL degrees, tomography tools, unit/regression test framework,
! improved CUDA GPUs performance, additonal GEOCUBIT support, better make compilation,
! git versioning system.
!
! MPI v. 2.1, July 2012:
! Max Rietmann, Peter Messmer, Daniel Peter, Dimitri Komatitsch, Joseph Charles, Zhinan Xie:
! support for CUDA GPUs, better CFL stability for the Stacey absorbing conditions.
!
! MPI v. 2.0, November 2010:
! Dimitri Komatitsch, Nicolas Le Goff, Roland Martin and Pieyre Le Loher, University of Pau, France,
! Daniel Peter, Jeroen Tromp and the Princeton group of developers, Princeton University, USA,
! and Emanuele Casarotti, INGV Roma, Italy:
!  support for CUBIT meshes decomposed by SCOTCH;
!  much faster solver using Michel Deville's inlined matrix products.
!
! MPI v. 1.4 Dimitri Komatitsch, University of Pau, Qinya Liu and others, Caltech, September 2006:
!  better adjoint and kernel calculations, faster and better I/Os
!  on very large systems, many small improvements and bug fixes
!
! MPI v. 1.3 Dimitri Komatitsch, University of Pau, and Qinya Liu, Caltech, July 2005:
!  serial version, regular mesh, adjoint and kernel calculations, ParaView support
!
! MPI v. 1.2 Min Chen and Dimitri Komatitsch, Caltech, July 2004:
!  full anisotropy, volume movie
!
! MPI v. 1.1 Dimitri Komatitsch, Caltech, October 2002: Zhu's Moho map, scaling
!  of Vs with depth, Hauksson's regional model, attenuation, oceans, movies
!
! MPI v. 1.0 Dimitri Komatitsch, Caltech, USA, May 2002: first MPI version based on global code
!
! Dimitri Komatitsch, IPG Paris, France, December 1996: first 3-D solver for the CM-5 Connection Machine,
!    parallelized on 128 processors using Connection Machine Fortran
!

! in case of an acoustic medium, a potential Chi of (density * displacement) is used as in Chaljub and Valette,
! Geophysical Journal International, vol. 158, p. 131-141 (2004) and *NOT* a velocity potential
! as in Komatitsch and Tromp, Geophysical Journal International, vol. 150, p. 303-318 (2002).
!
! This permits acoustic-elastic coupling based on a non-iterative time scheme.
! Displacement is then:
!     u = grad(Chi) / rho
! Velocity is then:
!     v = grad(Chi_dot) / rho
! (Chi_dot being the time derivative of Chi)
! and pressure is:
!     p = - Chi_dot_dot
! (Chi_dot_dot being the time second derivative of Chi).
!
! The source in an acoustic element is a pressure source.
!
! First-order acoustic-acoustic discontinuities are also handled automatically
! because pressure is continuous at such an interface, therefore Chi_dot_dot
! is continuous, therefore Chi is also continuous, which is consistent with
! the spectral-element basis functions and with the assembling process.
! This is the reason why a simple displacement potential u = grad(Chi) would
! not work because it would be discontinuous at such an interface and would
! therefore not be consistent with the basis functions.

! ************** PROGRAM STARTS HERE **************

  ! MPI initialization
  call init_mpi()

  ! force Flush-To-Zero if available to avoid very slow Gradual Underflow trapping
  call force_ftz()

  ! reads in parameters
  call initialize_simulation()

  ! reads in external mesh
  if (ADIOS_FOR_MESH) then
    ! ADIOS file format
    call read_mesh_databases_adios()
  else
    ! binary file
    call read_mesh_databases()
  endif

  ! reads in moho mesh
  if (ADIOS_FOR_MESH) then
    ! ADIOS file format
    call read_mesh_databases_moho_adios()
  else
    ! binary file
    call read_mesh_databases_moho()
  endif

  ! reads adjoint parameters
  call read_mesh_databases_adjoint()

  ! sets up reference element GLL points/weights/derivatives
  call setup_GLL_points()

  ! detects surfaces
  call detect_mesh_surfaces()

  ! setup receivers, allocates seismograms
  call setup_receivers_only()
  call setup_receivers_VTKfile()

  ! user output infos
  call prepare_timerun_user_output()

  ! sets up mass matrices
  call prepare_timerun_mass_matrices()

  ! sets up time increments
  call prepare_timerun_constants()

  ! initializes fault rupture arrays
  call prepare_timerun_faults()

  ! wavefield points on invgrid and write of ASKI main file, allocates ASKI_indx_local and ASKI_np_local_all
  ! and other arrays whose dimensions do not change with source. Exceptions: ASKI_efactors
  call prepare_timerun_ASKI()

  ! calculates gravity arrays minus_deriv_gravity, minus_g
  call prepare_gravity()

  ! prepares C-PML arrays, allocates and calculates convolution coefficients
  if (PML_CONDITIONS) call prepare_timerun_pml()

  ! prepares noise simulations, allocates and calculates noise arrays,
  call prepare_noise()

  ! Stacey boundaries, opens b_absorb_field and opens Stacey output file, closed in finalize
  call prepare_timerun_stacey()

  ! allocates arrays for source
  call allocate_arrays_for_sources()

  ! optimizes array memory layout for better performance,
  ! allocates dummy deriv_mapping, checks indexing of irregular elements, bandwidth test
  call prepare_optimized_arrays()

  ! check for presence of adjoint sources, allocates source_adjoint and zeros
  call setup_adjoint_sources()

  ! read attenuation database, gets constants
  call prepare_attenuation()

  ! ZN I do not use if (USE_LDDRK) call prepare_timerun_lddrk()
  ! ZN in order to avoid the error of using unallocated arrays later on in the code,
  ! ZN since R_**_lddrk are arguments in subroutine compute_forces_viscoelastic
  ! allocates diverse array
  call prepare_timerun_lddrk()

  !  allocate moment tensor derivs
  call allocate_moment_tensor_derivatives()

  ! prepares coupling with injection boundary, allocates and zeros diverse arrays for FK injection
  ! does not work with sequential sources
  call couple_with_injection_prepare_boundary()

  !  loop over multiple sequential sources
  do while (ANOTHER_SEQUENTIAL_SOURCE)

    ! for coupling with external codes,
    ! gets sequential injection source with NSTEP, GEMINI_SYNSEIS_FILE, ASKI_output_ID,
    !                            write_aski_main (eliminate that), ASKI_outfile and SEISMO_PATH
    ! updates NSTEP and NTSTEP_BETWEEN_OUTPUT_SEISMOS = NSTEP
    ! opens injected wavefields HDF file, GEMINI_TLEN, GEMINI_DT
    call couple_with_injection_setup()

    ! defines name of source file, allocs comp_dir_vect_* and factor_for_source
    ! locates sources and sets up source time function and simulation start time, prints STF
    ! gets sequential force or cmt source
    call setup_sources()

    ! pre-compute sourcearrays field,
    ! deallocs comp_dir_vect_* and factor_for_source
    call setup_sources_precompute_arrays()

    ! write source VTK files for Paraview, opens VTK file and writes src points and closes VTK
    call setup_sources_VTKfile()

    ! allocate seismograms here with exact length
    ! nlength_seismogram is set here
    call allocate_receivers_seismograms()

    ! zero receiver seismograms
    call zero_receivers_seismograms()

    ! zeros disp, veloc, accel arrays, and set iglob_check_elastic etc
    call prepare_wavefields()

    ! zero attenuation arrays
    call clear_attenuation_arrays()

    ! clear lddrk arrays
    call zero_lddrk_arrays()

    ! prepares ADJOINT simulations, zeros lots of arrays
    call prepare_timerun_adjoint()

    ! allocate and set efactors. Compute stf spectrum. Zero other ASKI arrays
    ! allocates also ASKI_efactors_re/im and computes them
    ! computes ASKI taper start
    call prepare_ASKI_output()

    ! prepares GPU arrays for first run, then only updates
    if (GPU_MODE) then
      if (current_sequential_source == 1) then
        call prepare_GPU()
        call prepare_ASKI_GPU()
      else
        call update_GPU()
        call update_ASKI_GPU()
     end if
    end if

    ! synchronize all the processes
    call synchronize_all()

#ifdef VTK_VIS
    ! vtk window in-situ visualization
    call vtk_window_prepare()
#endif

    ! steps through time iterations
    ! also transfers from GPU and cleans up GPU
    if (UNDO_ATTENUATION_AND_OR_PML) then
      call iterate_time_undoatt()
    else
      call iterate_time()
    endif

    !  save ASKI output (WF), deallocates ASKI efactors
    call save_ASKI_output()

    ! deallocate seismograms before going to next source
    deallocate(seismograms_d,seismograms_v,seismograms_a,seismograms_p)

    ! save current state of some output files
    !if (myrank == 0) then
    !  call system("cp OUTPUT_FILES/output_solver.txt "//trim(ASKI_outfile)//"_OUTPUT_FILES")
    !  call system("cp OUTPUT_FILES/output_list_sources.txt "//trim(ASKI_outfile)//"_OUTPUT_FILES")
    !  call system("cp OUTPUT_FILES/output_list_stations.txt "//trim(ASKI_outfile)//"_OUTPUT_FILES")
    !  call system("cp OUTPUT_FILES/plot_source_time_function.txt "//trim(ASKI_outfile)//"_OUTPUT_FILES")
    !  call system("cp OUTPUT_FILES/receivers.vtk "//trim(ASKI_outfile)//"_OUTPUT_FILES")
    !  call system("cp OUTPUT_FILES/sources.vtk "//trim(ASKI_outfile)//"_OUTPUT_FILES")
    !endif

    ! update variables for multiple sequential sources case
    if (MULTIPLE_SEQUENTIAL_SOURCES) then
      if (current_sequential_source < num_sequential_sources) then
        current_sequential_source = current_sequential_source + 1
        ANOTHER_SEQUENTIAL_SOURCE = .true.
      else
        ANOTHER_SEQUENTIAL_SOURCE = .false.
     endif
    else
      ANOTHER_SEQUENTIAL_SOURCE = .false.
    endif
  enddo         ! end multiple sequential sources loop

  ! finishes kernel calculations
  call finalize_simulation()

  ! MPI finish
  call finalize_mpi()

  end program xspecfem3D

